#!/usr/bin/env bash
#
# Bootstrap android-ui-analyser for Claude Code and Codex.
#
# Installs the `aua` CLI GLOBALLY (so it's on PATH in every project) and installs the
# equivalent user-level skills so agents discover it in every project. Idempotent.
#
# Usage:  ./install.sh
#
# We intentionally do NOT use `set -e`: global installs are attempted with explicit
# fallback to a project-local venv, so a failed `uv`/`pipx` step must not abort the script.
set -uo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_DIR"

# Core hierarchy analysis needs NO extras (uiautomator2 is a base dependency). OCR powers the
# vision fallback on Compose/Flutter/WebView/canvas screens the accessibility tree can't see.
case "$(uname -s)" in
  Darwin) OCR_PKGS=(pyobjc-framework-Vision pyobjc-framework-Quartz rapidocr-onnxruntime onnxruntime); EXTRA="apple,rapidocr,audio" ;;
  *)      OCR_PKGS=(rapidocr-onnxruntime onnxruntime);                                                 EXTRA="rapidocr,audio" ;;
esac
AUDIO_PKGS=(grpcio)
FEATURE_PKGS=("${OCR_PKGS[@]}" "${AUDIO_PKGS[@]}")

export PATH="$HOME/.local/bin:$PATH"   # where uv/pipx drop console scripts
AUA=""

install_global() {
  if command -v uv >/dev/null 2>&1; then
    echo "==> Installing the 'aua' CLI globally with uv tool..."
    local with=(); local p; for p in "${FEATURE_PKGS[@]}"; do with+=(--with "$p"); done
    # --reinstall: --force alone reuses uv's cached wheel when the version string has not
    # changed, so editing the source and re-running installed the OLD code silently.
    # --editable: the console script then imports straight from this clone, so `git pull`
    # updates the CLI and the daemon can never load different bytes than the caller.
    if uv tool install --force --reinstall --editable "${with[@]}" "$REPO_DIR"; then
      uv tool update-shell >/dev/null 2>&1 || true
      AUA="aua"; return 0
    fi
    echo "    uv tool install failed; trying the next option..."
  fi
  if command -v pipx >/dev/null 2>&1; then
    echo "==> Installing the 'aua' CLI globally with pipx..."
    if pipx install --force --editable "$REPO_DIR"; then
      pipx inject android-ui-analyser "${FEATURE_PKGS[@]}" >/dev/null 2>&1 \
        || echo "    (optional OCR/audio dependencies not added — core CLI still works)"
      pipx ensurepath >/dev/null 2>&1 || true
      AUA="aua"; return 0
    fi
    echo "    pipx install failed; falling back to a local venv..."
  fi
  return 1
}

install_venv() {
  echo "==> pipx/uv unavailable — installing into a project-local venv (.venv)."
  echo "    NOTE: this makes 'aua' available only via $REPO_DIR/.venv/bin/aua, not globally."
  echo "    For a GLOBAL 'aua', install pipx (python3 -m pip install --user pipx) and re-run."
  python3 -m venv .venv || { echo "ERROR: could not create venv"; exit 1; }
  ./.venv/bin/python -m ensurepip --upgrade >/dev/null 2>&1 || true
  ./.venv/bin/python -m pip install -q --upgrade pip
  ./.venv/bin/python -m pip install -q -e ".[${EXTRA}]" || { echo "ERROR: pip install failed"; exit 1; }
  AUA="$REPO_DIR/.venv/bin/aua"
}

install_global || install_venv

# Resolve a runnable aua (prefer the global one; fall back to the venv path).
if ! command -v "$AUA" >/dev/null 2>&1 && [ ! -x "$AUA" ]; then
  AUA="$REPO_DIR/.venv/bin/aua"
fi

echo "==> Installing the Claude Code skill at user level (~/.claude/skills)..."
"$AUA" guide --emit-skill "$HOME/.claude/skills/android-ui-analyser/SKILL.md"

# Codex discovers personal skills under $CODEX_HOME/skills (default ~/.codex/skills). The skill
# body is byte-identical to Claude's; agents/openai.yaml is UI metadata, generated by guide.py.
AUA_CODEX_ROOT="${CODEX_HOME:-$HOME/.codex}/skills/android-ui-analyser"
echo "==> Installing the Codex skill at user level ($AUA_CODEX_ROOT)..."
"$AUA" guide --emit-skill "$AUA_CODEX_ROOT/SKILL.md"
mkdir -p "$AUA_CODEX_ROOT/agents"
"$AUA" guide --emit-codex-metadata "$AUA_CODEX_ROOT/agents/openai.yaml"

# Optional AOT thin client — skips Python startup when talking to a warm daemon.
if command -v cc >/dev/null 2>&1 || command -v clang >/dev/null 2>&1; then
  echo "==> Building optional aua-fast (C daemon client)..."
  if make -C "$REPO_DIR/native/aua-fast" install; then
    echo "    installed to ~/.local/bin/aua-fast (use after: aua daemon start)"
  else
    echo "    (aua-fast build skipped — 'aua' still works; see native/aua-fast/README.md)"
  fi
else
  echo "==> Skipping aua-fast (no C compiler). Install later: make -C native/aua-fast install"
fi

echo
echo "==> Verifying environment (aua doctor):"
"$AUA" doctor || true

cat <<EOF

────────────────────────────────────────────────────────────────────────────
✓ Setup complete.
  • 'aua' CLI installed ($AUA)
  • Skill installed at ~/.claude/skills/android-ui-analyser/ — active in EVERY project
  • Skill installed at $AUA_CODEX_ROOT — available to Codex in every project
  • Optional: 'aua-fast' (if built) for lower latency against a warm daemon

Next steps:
  1. Connect an Android device or emulator   (README → "Connect a device or emulator")
  2. Run 'aua doctor' until adb + devices show OK
  3. In any project, ask Claude Code or Codex to test your Android app. Start with
     'aua session start --goal "<what to verify>"'. Operating manual: 'aua guide --brief'.
────────────────────────────────────────────────────────────────────────────
EOF
