"""Hierarchy parser tests (PRD §13.1 AC2).

The three fixtures cover the shapes the gate must distinguish later:
- ``normal_views``        — a well-instrumented Views screen
- ``compose_no_semantics``— Compose with empty/merged nodes, no readable text
- ``empty_canvas``        — a single full-screen SurfaceView (game/canvas)

Golden ``*.json`` files were generated by this parser and eyeballed for correct
filtering and ID order; each test asserts the live parse still matches its golden.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from android_ui_analyser.hierarchy import parse_hierarchy
from android_ui_analyser.schema import Source

FIXTURES = Path(__file__).parent / "fixtures"
SCREEN = (1080, 2400)
FIXTURE_NAMES = ["normal_views", "compose_no_semantics", "empty_canvas"]


def _dump(name: str) -> list[dict]:
    xml = (FIXTURES / f"{name}.xml").read_text(encoding="utf-8")
    return [e.model_dump(mode="json") for e in parse_hierarchy(xml, SCREEN)]


@pytest.mark.parametrize("name", FIXTURE_NAMES)
def test_parse_matches_golden(name: str) -> None:
    golden = json.loads((FIXTURES / f"{name}.json").read_text(encoding="utf-8"))
    assert _dump(name) == golden


@pytest.mark.parametrize("name", FIXTURE_NAMES)
def test_ids_are_dense_and_reading_ordered(name: str) -> None:
    els = parse_hierarchy((FIXTURES / f"{name}.xml").read_text(encoding="utf-8"), SCREEN)
    # ids are 0..n-1 in order
    assert [e.id for e in els] == list(range(len(els)))
    # sorted top-to-bottom then left-to-right
    keys = [(e.bounds[1], e.bounds[0]) for e in els]
    assert keys == sorted(keys)


def test_all_elements_source_hierarchy() -> None:
    els = parse_hierarchy((FIXTURES / "normal_views.xml").read_text(encoding="utf-8"), SCREEN)
    assert all(e.source is Source.hierarchy for e in els)
    assert all(e.confidence is None for e in els)


def test_normal_views_keeps_labeled_controls() -> None:
    els = parse_hierarchy((FIXTURES / "normal_views.xml").read_text(encoding="utf-8"), SCREEN)
    by_text = {e.text: e for e in els if e.text}
    assert "Log in" in by_text
    login = by_text["Log in"]
    assert login.type == "Button"
    assert login.clickable is True
    assert login.resource_id == "com.example.shop:id/login_btn"
    # password EditText carries its content-desc, no text
    pwd = next(e for e in els if e.content_desc == "Password")
    assert pwd.text is None
    assert pwd.type == "EditText"


def test_layout_containers_are_filtered_out() -> None:
    els = parse_hierarchy((FIXTURES / "normal_views.xml").read_text(encoding="utf-8"), SCREEN)
    # the pure FrameLayout/LinearLayout wrappers carry no text and aren't actionable
    types = {e.type for e in els}
    assert "FrameLayout" not in types
    assert "LinearLayout" not in types


def test_empty_canvas_single_surfaceview() -> None:
    els = parse_hierarchy((FIXTURES / "empty_canvas.xml").read_text(encoding="utf-8"), SCREEN)
    assert len(els) == 1
    assert els[0].type == "SurfaceView"
    assert els[0].text is None


def test_compose_keeps_scrollable_container_and_leaves() -> None:
    els = parse_hierarchy(
        (FIXTURES / "compose_no_semantics.xml").read_text(encoding="utf-8"), SCREEN
    )
    # the scrollable non-leaf View is kept (actionable); leaf Views are kept too
    assert any(e.bounds == (0, 84, 1080, 2400) for e in els)  # scrollable container
    assert len(els) == 5
    assert all(e.text is None and e.content_desc is None for e in els)


# --------------------------------------------------------------------------- unit rules


def _xml(*nodes: str) -> str:
    return f'<hierarchy rotation="0">{"".join(nodes)}</hierarchy>'


def _node(**attrs: object) -> str:
    defaults = {
        "text": "",
        "resource-id": "",
        "class": "android.view.View",
        "package": "com.x",
        "content-desc": "",
        "checkable": "false",
        "clickable": "false",
        "enabled": "true",
        "focused": "false",
        "long-clickable": "false",
        "scrollable": "false",
        "password": "false",
    }
    defaults.update({k.replace("_", "-"): v for k, v in attrs.items()})
    body = " ".join(f'{k}="{v}"' for k, v in defaults.items())
    return f"<node {body} />"


def test_zero_area_nodes_dropped() -> None:
    xml = _xml(
        _node(text="real", bounds="[0,0][100,100]"),
        _node(text="degenerate-w", bounds="[10,10][10,50]"),
        _node(text="degenerate-h", bounds="[10,10][50,10]"),
        _node(text="inverted", bounds="[50,50][10,10]"),
    )
    els = parse_hierarchy(xml)
    assert [e.text for e in els] == ["real"]


def test_offscreen_nodes_dropped_only_with_screen_size() -> None:
    xml = _xml(
        _node(text="on", bounds="[0,0][100,100]"),
        _node(text="off-right", bounds="[2000,0][2100,100]"),
        _node(text="off-below", bounds="[0,3000][100,3100]"),
        _node(text="partial", bounds="[-10,-10][20,20]"),
    )
    # no screen size: everything with area is kept
    assert {e.text for e in parse_hierarchy(xml)} == {"on", "off-right", "off-below", "partial"}
    # with screen size: fully off-screen dropped, partial overlap kept
    els = parse_hierarchy(xml, (1080, 2400))
    assert {e.text for e in els} == {"on", "partial"}


def test_bounds_and_center_and_short_type() -> None:
    xml = _xml(
        _node(text="t", **{"class": "android.widget.ImageButton"}, bounds="[10,20][110,220]")
    )
    (el,) = parse_hierarchy(xml)
    assert el.bounds == (10, 20, 110, 220)
    assert el.center == (60, 120)
    assert el.type == "ImageButton"


def test_empty_string_attrs_become_none() -> None:
    xml = _xml(_node(text="", content_desc="", resource_id="", bounds="[0,0][50,50]"))
    (el,) = parse_hierarchy(xml)  # kept as a leaf
    assert el.text is None
    assert el.content_desc is None
    assert el.resource_id is None


def test_non_leaf_unactionable_container_dropped_but_child_kept() -> None:
    xml = _xml(
        '<node class="android.widget.LinearLayout" text="" resource-id="" package="com.x" '
        'content-desc="" checkable="false" clickable="false" enabled="true" focused="false" '
        'long-clickable="false" scrollable="false" password="false" bounds="[0,0][500,500]">'
        + _node(text="child", bounds="[10,10][100,100]")
        + "</node>"
    )
    els = parse_hierarchy(xml)
    assert [e.text for e in els] == ["child"]
    assert "LinearLayout" not in {e.type for e in els}


def test_boolean_attrs_parsed() -> None:
    xml = _xml(
        _node(text="b", clickable="true", enabled="false", focused="true", bounds="[0,0][50,50]")
    )
    (el,) = parse_hierarchy(xml)
    assert el.clickable is True
    assert el.enabled is False
    assert el.focused is True


def test_empty_xml_returns_empty_list() -> None:
    assert parse_hierarchy("") == []
    assert parse_hierarchy("   ") == []
    assert parse_hierarchy('<hierarchy rotation="0"></hierarchy>') == []
