"""Pluggable platform strategies used by the AUA engine."""

from ..providers.base import Bounds, ScreenImage
from ..schema import AppContext, DeviceInfo, Element, MatchMode, ShellResult, TargetInfo
from .base import AppBundle, DiscoveredTarget, InstalledApp, NormalizedTree, PlatformAdapter
from .conformance import (
    ATTACHED_TARGET_CAPABILITIES,
    AttachedTargetCase,
    AttachedTargetReport,
    PlatformConformanceError,
    run_attached_target_conformance,
)
from .contracts import (
    ADAPTER_CAPABILITIES,
    DIRECT_CAPABILITIES,
    RUNTIME_CAPABILITIES,
    CapabilityScope,
    CapabilitySpec,
)
from .diagnostics import (
    DIAGNOSTIC_LEVEL_CODES,
    AppExitEvidence,
    CrashEvidence,
    DiagnosticEvent,
    DiagnosticLevel,
    DiagnosticSourcePolicy,
    DiagnosticWindow,
    UnknownDiagnosticMark,
)
from .geometry import DisplayGeometry
from .identity import AppLike, AppRef, TargetLike, TargetRef, app_ref, target_ref
from .registry import (
    ENTRY_POINT_GROUP,
    PLATFORM_API_VERSION,
    PlatformFactory,
    available_platforms,
    register_platform,
    registered_platforms,
)
from .runtime import TargetRuntime
from .services import (
    APP_DATABASE,
    CAPABILITY_METHODS,
    DEVELOPER_SETTINGS,
    DEVICE_AGENT,
    FEATURE_FLAGS,
    MICROPHONE,
    NETWORK,
    NETWORK_PROFILES,
    PROXY,
    TARGET_SUPERVISION,
    VIRTUAL_DEVICES,
    VIRTUAL_TARGETS,
    WEBVIEW,
    TargetSupervisionService,
    VirtualTargetsService,
)
from .supervision import TargetSupervisionStatus
from .virtual_targets import (
    OwnedVirtualTargetStopRequest,
    VirtualTargetCreateRequest,
    VirtualTargetCreateResult,
    VirtualTargetDefinition,
    VirtualTargetDeleteRequest,
    VirtualTargetDeleteResult,
    VirtualTargetInstance,
    VirtualTargetList,
    VirtualTargetProvisionRequest,
    VirtualTargetReclaimRequest,
    VirtualTargetStartRequest,
    VirtualTargetStatus,
    VirtualTargetStopRequest,
    VirtualTargetStopResult,
)

__all__ = [
    "ADAPTER_CAPABILITIES",
    "APP_DATABASE",
    "ATTACHED_TARGET_CAPABILITIES",
    "ENTRY_POINT_GROUP",
    "AppBundle",
    "AppContext",
    "AppExitEvidence",
    "AppLike",
    "AppRef",
    "AttachedTargetCase",
    "AttachedTargetReport",
    "Bounds",
    "CAPABILITY_METHODS",
    "CapabilityScope",
    "CapabilitySpec",
    "InstalledApp",
    "CrashEvidence",
    "DIAGNOSTIC_LEVEL_CODES",
    "DEVELOPER_SETTINGS",
    "DEVICE_AGENT",
    "DIRECT_CAPABILITIES",
    "DiagnosticEvent",
    "DiagnosticLevel",
    "DiagnosticSourcePolicy",
    "DiagnosticWindow",
    "DisplayGeometry",
    "DiscoveredTarget",
    "DeviceInfo",
    "Element",
    "FEATURE_FLAGS",
    "MICROPHONE",
    "MatchMode",
    "NETWORK",
    "NETWORK_PROFILES",
    "NormalizedTree",
    "PLATFORM_API_VERSION",
    "PROXY",
    "PlatformAdapter",
    "PlatformConformanceError",
    "PlatformFactory",
    "RUNTIME_CAPABILITIES",
    "ScreenImage",
    "ShellResult",
    "TARGET_SUPERVISION",
    "TargetRuntime",
    "TargetSupervisionService",
    "TargetSupervisionStatus",
    "TargetLike",
    "TargetRef",
    "TargetInfo",
    "UnknownDiagnosticMark",
    "VIRTUAL_DEVICES",
    "VIRTUAL_TARGETS",
    "VirtualTargetsService",
    "WEBVIEW",
    "OwnedVirtualTargetStopRequest",
    "VirtualTargetCreateRequest",
    "VirtualTargetCreateResult",
    "VirtualTargetDefinition",
    "VirtualTargetDeleteRequest",
    "VirtualTargetDeleteResult",
    "VirtualTargetInstance",
    "VirtualTargetList",
    "VirtualTargetProvisionRequest",
    "VirtualTargetReclaimRequest",
    "VirtualTargetStartRequest",
    "VirtualTargetStatus",
    "VirtualTargetStopRequest",
    "VirtualTargetStopResult",
    "available_platforms",
    "app_ref",
    "register_platform",
    "registered_platforms",
    "run_attached_target_conformance",
    "target_ref",
]
